# Generated by Django 5.1.5 on 2025-02-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='hours_worked',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
