# Generated by Django 5.1.5 on 2025-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_guard',
            field=models.BooleanField(default=False),
        ),
    ]
