# Generated by Django 5.1.5 on 2025-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='minutes_late',
            field=models.IntegerField(default=0),
        ),
    ]
