# Generated by Django 5.1.5 on 2025-03-23 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_customuser_email_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
