# Generated by Django 5.1.5 on 2025-02-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_customuser_is_guard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
