# Generated by Django 5.1.5 on 2025-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='checkout_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='checkout_location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='checkout_location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='checkout_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
