# Generated by Django 5.1.5 on 2025-02-28 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_customuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('navigation', 'Navigation'), ('announcement_create', 'Announcement Created'), ('announcement_post', 'Announcement Posted'), ('announcement_delete', 'Announcement Deleted'), ('excel_import', 'Excel Import'), ('excel_export', 'Excel Export'), ('leave_approval', 'Leave Approval'), ('login', 'User Login'), ('logout', 'User Logout'), ('admin_create', 'Admin Create'), ('admin_update', 'Admin Update'), ('admin_delete', 'Admin Delete')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
