# Generated by Django 5.1.5 on 2025-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_adminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('navigation', 'Navigation'), ('announcement_create', 'Announcement Created'), ('announcement_post', 'Announcement Posted'), ('announcement_delete', 'Announcement Deleted'), ('_import', 'Excel Import'), ('excel_export', 'Excel Export'), ('leave_approval', 'Leave Approval'), ('login', 'User Login'), ('logout', 'User Logout'), ('admin_create', 'Admin Create'), ('admin_update', 'Admin Update'), ('admin_delete', 'Admin Delete')], max_length=30),
        ),
    ]
