# Generated by Django 5.1.5 on 2025-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_adminlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('navigation', 'Navigation'), ('announcement_create', 'Announcement Created'), ('announcement_post', 'Announcement Posted'), ('announcement_delete', 'Announcement Deleted'), ('leave_approval', 'Leave Approval'), ('login', 'User Login'), ('logout', 'User Logout'), ('admin_create', 'Admin Create'), ('admin_update', 'Admin Update'), ('admin_delete', 'Admin Delete')], max_length=30),
        ),
    ]
