# Generated by Django 5.1.5 on 2025-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
