# Generated by Django 5.1.5 on 2025-03-05 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_customuser_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leave_credits',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
