# Generated by Django 5.1.5 on 2025-03-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_customuser_leave_credits_customuser_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Leave Types',
                'db_table': 'django_leave_types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.leavetype'),
        ),
    ]
