# Generated by Django 5.1.5 on 2025-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_leavetype_alter_leave_options_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether this leave type uses leave credits'),
        ),
    ]
